### ISSUE TITLE
ドキュメンテーションの整形がおかしい

### ISSUE THREAD

**Issue by ftkro** [payjp/payjp-php#12]
https://github.com/payjp/payjp-php/blob/master/RequestExample.md
上記のMarkdownで見出しとなる
```#```
の後ろの文字にスペースが空いていないためか、見出しにならず単なるテキストになっています(ほぼ全て)。
こちらの修正をお願いします。なお、PRで対応するべきでしたらその旨ご連絡ください。速やかに対応させていただきます。

**Comment by wozozo** [comment]
https://github.com/payjp/payjp-php/commit/a6b1d77be50e25acb7270ca1bd5b826266344fe0
修正しました！ 🙇
